name: ci

on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry via pip
        run: pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run tests via task test
        run: poetry run task test
